version: '3'

services:
  shoppingcart:
    image: drumsaling/shopping:1.0
    ports:
      - 8080:8080

  mysql:
    image: mysql:8
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Caganera@123
      MYSQL_USER: Root
      MYSQL_PASSWORD: Caganera@123
      MYSQL_DATABASE: shopping-cart
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
      MYSQL_INITDB_SCRIPT: /docker-entrypoint-initdb.d/mysql_query.sql
    ports:
      - 3308:3306
    command: ["--event-scheduler=ON"]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./databases:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 1


volumes:
  mysql_data:



